name: Example PR Workflow
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths:
      - '**/tools.csv'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          tr '\n' '//' < ./ictst/data/tools.csv
          # Note: the following account information will not work on GHES
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "remove new line and replace with //"
          git push
